# Generated by Django 4.1.7 on 2023-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDBApp', '0002_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('sub1', models.TextField()),
                ('sub2', models.TextField()),
                ('sub3', models.TextField()),
                ('sub4', models.TextField()),
                ('sub5', models.TextField()),
                ('total', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
