# Generated by Django 4.1.7 on 2023-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDBApp', '0003_student1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='total',
        ),
        migrations.AlterField(
            model_name='student1',
            name='sub1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='sub2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='sub3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='sub4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student1',
            name='sub5',
            field=models.IntegerField(),
        ),
    ]
